title: Expeditions
email: williamnorton09@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Uncharted Waters
baseurl: "/Expeditions" # the subpath of your site, e.g. /blog
url: "https://smashxanadu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  smashxanadu

# Build settings
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
 enabled: true
 collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
remote_theme: pages-themes/minimal@v0.2.0
markdown: kramdown
lsi: false
safe: true
source: /Expeditions
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
